package ics

const (
	TOKEN_CAL_START   = "BEGIN:VCALENDAR"
	TOKEN_CAL_END     = "END:VCALENDAR"
	TOKEN_DESCRIPTION = "DESCRIPTION:"
	TOKEN_DTSTART     = "DTSTART:"
	TOKEN_DTSTAMP     = "DTSTAMP:"
	TOKEN_DTEND       = "DTEND:"
	TOKEN_EVENT_START = "BEGIN:VEVENT"
	TOKEN_EVENT_END   = "END:VEVENT"
	TOKEN_LOCATION    = "LOCATION:"
	TOKEN_METHOD      = "METHOD:"
	TOKEN_PRODID      = "PRODID:"
	TOKEN_SUMMARY     = "SUMMARY:"
	TOKEN_UID         = "UID:"
	TOKEN_VERSION     = "VERSION:2.0"
)
